# Documentation: https://roots.io/trellis/docs/remote-server-setup/
wordpress_sites:
  healthedservices.com:
    site_hosts:
      - 198.211.117.125
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:Blue-Pine-Studio/healthedservices.git # replace with your Git repo URL
    branch: production
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
      # cert: ~/ssl/example.com.crt
      # key: ~/ssl/example.com.key
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://198.211.117.125
      wp_siteurl: http://198.211.117.125/wp
      wp_env: production
      db_name: healthedservices_prod
      db_user: healthedservices_dbuser
      # Define the following variables in group_vars/production/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
